language: node_js
node_js:
  - 8
before_install:
  - npm i -g firebase-tools
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  project: react-app
  skip_cleanup: true
  token: twauUTmTHe-GMKIjUNEApA