language: node_js
node_js:
  - 8
before_install:
  - npm i -g firebase-tools
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  project: react-app
  skip_cleanup: true
  token: M5Rv/ActchHgOp1P9hDrvuEJojGo+qjJjjnScQ5No0bI4IRRJdcXexJmCkSF8RA3B6VjfDf0t7OQSCyiH9UAyncYilnxwR5usjUsmFdJN/HZbOZK/NZlN9vvj6bMDgHS418JRCnb/lA98DEoSk86ds1vBDiRT22ozAkbpJD62Y9Wq6YrcU0E5uG1Evn2Sw9+tDdFsn0nF9grqBlNanac/NNB2h1RXe5ZvtK9WWzcjeQ7BqQirmsahQLHkcLtDzknlXFk7HOfKaD/Qu0wT5WYH2QLwvcJV+eSXVEeGP15hVx+ZqighiLTfttZt/37FXEyRIVHjEnHyTlpqEM/kT7opcfqNMQLGQLz5hGtmEbwVMt0ay4xrgwvp0+DhxK2upsZ1k0FQQi8cTDR7FjSTw9XH15EzEAvrhRv9H3i+CYyjfYxPGh4BSCngk4ELjJKnGBz6nIgIyDcpg2p9JTlMOK78Fva1Yw1r/y+PkZOf5zZinYiyK/ZzDMevwd0LQmb5+lSPaMzGOn/hwuuIZXSaPzQK+eEtlOG2llM5ZTzfDSd9T32/GCKP4lfmVMOwbbH4e2oaIMLJMnEVJwvRzgvtA8Y/mVNCUg+jPNPm9lbtsL7S0keVH5ttG5DVorA+yZ8HNulO/C+g/GN0H6LD637dVd+b+VPYNMz65dU/qi4DOxiNvY=