language: node_js
node_js:
- 8
before_install:
- npm i -g firebase-tools
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: firebase
  project: react-app
  skip_cleanup: true
  token:
    secure: OeZekLRTwZnh0L6LtM4dhGEY6+HDHsWKCGvRNqi9+aCKfjOVq5mDkrc83cDJeKBOpJHvzD9SW/bwEaTSNEKYn85Za9gqCUM4G5WrOqhgNacQP0wYHA8vuvNtF3E8ru8Td7wDSdlalhs7l8kVVUBG+8HGhOuJ7WbAC1AjLaoSbpmEC9foyUp55r6WU/CNhSArX8DhAOsHmsDAelciSnTTCj7WC2fSlyUFJX62tq0l55NiMHDAlscnY9knhnqnCp8ZXXFuSd1ZXblUBOKYii4EmpkfCZzF8mq8qDO3rVcnTggha+EkJfOu6wzWQ50+aICaPKJTEDV0UvHajzWV2f31FCz8K7vWDCJBWnZeOHPB17ejpCunWmZvdlJER6Ufw7A7tkBzmgYzPzLyICxWWFR+JAtbadHFTlf9A6vs7dH/xukrphBeuv9YHFuVuF9bJpn2AivEUCjUCsN+mE2FW3JchFwKSeoKCL/zKpZvTWvLZHWQm2lcR4FoOwWXkCeUvQx2r8KAhIIm7Eh1Ne+TgdCe22MnGKyzGKTXu2jnM3pcqc0mnYAAcRHF+ZFKosSASB5mVuPwsNP3fu10+M0ikjPfTvysJzewtUdLUg+dgFQeLZAKIf9rhniVtXf8nP5gVbNNsmyk5mK6bd2W2KOq6T7P++HoFPqOrMniyx1hjGhGopQ=